### ISSUE TITLE
Doesn't work with Phaser 3.8 Plugin changes

### ISSUE THREAD

**Issue by jjttjj** [sebashwa/phaser-plugin-isometric#1]
There seem to be some issues with tis plugin and the changes to the plugin system in Phaser 3.8, seen here: https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md#new-plugin-manager

I can get the IsoPlugin loaded with 
```
this.load.scenePlugin({key: "IsoPlugin",
 url: IsoPlugin,
 sceneKey: "iso"});
```
But IsoPhysics is not working, I believe due to the way the plugin key is expected to be here:
https://github.com/sebashwa/phaser3-plugin-isometric/blob/master/src/physics/IsoPhysics.js#L24

I can continue to investigate this and try to put together a PR if you'd like.

**Comment by jjttjj** [comment]
I had something wrong on my end, this does work with the current version of phaser.

**Comment by MrMonotone** [comment]
@jjttjj Would you mind providing your example if you got it working? 

EDIT: Figured it out see #2
