### ISSUE TITLE
Better examples?

### ISSUE THREAD

**Issue by DylanC** [sebashwa/phaser-plugin-isometric#5]
Would it be possible to have better examples of usage with demo and code provided? Like this - http://rotates.org/phaser/iso/examples/interaction.htm

**Comment by sebashwa** [comment]
I would love to put more time and effort into this plugin, but actually I'm pretty busy with other stuff.
So at the moment I'm afraid you need to read the source code from the repository and run the examples locally / have a look at the github page.

Also feel free to add more examples in the provided structure / include something like code mirror and create a PR for it!

**Comment by DylanC** [comment]
@sebashwa - If I can understand it, I will. I did build my own isometric implementation in the meantime but its basic and pretty rough. I was hoping to use something more established but apparently according to Rich its coming in Phaser3. 

https://github.com/photonstorm/phaser/issues/3043

**Comment by sebashwa** [comment]
Cool, thanks for the hint! Looking forward to direct isometric support in phaser!

**Comment by t1gor** [comment]
Well, phaser 3 is here, but the ISO support is not as I'd expect it to be. Using your plugin guys 👍 great job on it.

I have a question though: are the tile maps supported with the plugin? So far I couldn't get it working as phaser just throws an error on isometric map. Any ideas how can I use it?

**Comment by sebashwa** [comment]
Hi @t1gor,

I'm afraid they are not supported at this very moment. 
I only ported the plugin to assure support with phaser 3. Referring an issue from the old repository:

https://github.com/lewster32/phaser-plugin-isometric/issues/35

Would be great to have support though.

Cheers
