### ISSUE TITLE
Animation not working ?

### ISSUE THREAD

**Issue by Biratus** [sebashwa/phaser-plugin-isometric#6]
Hi,
There seems to be an issue with the sprite update function, I ran into while creating animations...
Phaser now needs to be passed time and delta parameters. The issue is located in the preUpdate function of IsoSprite.js l.178-188. The Phaser.Sprite preUpdate function is called without those parameters, which then are not passed onto the update function resulting in subsequent problems.

```
  /**
   * Internal function called by the World update cycle.
   *
   * @method IsoSprite#preUpdate
   * @memberof IsoSprite
   */
  preUpdate() {
    Sprite.prototype.preUpdate.call(this);

    this._project();
  }
```

Fortunately, you just need to add time and delta in the preUpdate function of IsoSprite and call Sprite.preUpdate with them

Thanks

**Comment by sebashwa** [comment]
Hey Biratus,

thanks for the bug report! I never used animations so far.
Should be fixed with v0.0.7!

Cheers
