### ISSUE TITLE
Compatibility with Tiled?

### ISSUE THREAD

**Issue by mwcz** [sebashwa/phaser-plugin-isometric#7]
Hi!  I'm trying to load an isometric map created in [Tiled](https://www.mapeditor.org/).  I haven't been able to get it to work in Phaser 3, so I wanted to ask whether Tiled isometric maps are supported by this plugin.  Thanks!

**Comment by sebashwa** [comment]
Hi @mwcz,

sorry for the late reply. Unfortunately Tiled is not supported by this plugin either 😞 see [this issue](https://github.com/sebashwa/phaser3-plugin-isometric/issues/5#issuecomment-446478180)

Cheers

**Comment by mwcz** [comment]
No problem, thank you very much for the response.
