### ISSUE TITLE
Examples / Tutorial

### ISSUE THREAD

**Issue by aqilzeeshan** [sebashwa/phaser-plugin-isometric#8]
Hi,

Where can I find examples of it's usage and is there any tutorial with explanation ?

Thanks

**Comment by sebashwa** [comment]
Hey @aqilzeeshan,

you can find examples [here](https://github.com/sebashwa/phaser3-plugin-isometric/tree/master/docs/pages) and running examples of those [here](https://sebashwa.github.io/phaser3-plugin-isometric/). A tutorial is unfortunately not available at the moment.

Cheers
